_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
calculated_max_seq_len:
    value: 128
device:
    value: cuda
dropout:
    value: 0.1
embedding_dim:
    value: 256
epochs:
    value: 10
learning_rate:
    value: 0.01
transformer_heads:
    value: 8
transformer_hidden_dim:
    value: 512
transformer_layers:
    value: 3
